run:
  timeout: 3m
linters-settings:
  cyclop:
    max-complexity: 30
    package-average: 10.0
  errcheck:
    check-type-assertions: true
  exhaustive:
    check:
      - map
  funlen:
    lines: 100
    statements: 55
  gocognit:
    min-complexity: 20
  gocritic:
    settings:
      captLocal:
        paramsOnly: false
      underef:
        skipRecvDeref: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
    settings:
      shadow:
        strict: false
  lll:
    line-length: 210
    tab-width: 1
  nakedret:
    max-func-lines: 10
linters:
  disable-all: true
  enable:
    - cyclop
    # - depguard
    - errcheck
    # - exhaustive
    - exportloopref
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    # Broken with MacOS 13.x
    # - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    - nestif
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - funlen
        - lll
        - gochecknoglobals
    - path: "apis/*"
      linters:
        - gochecknoglobals
    - path: "metrics.go"
      linters:
        - gochecknoglobals
    - path: "metrics.go"
      linters:
        - gochecknoglobals"
    - path: "controller.go"
      linters:
        - lll
    - path: "webhook.go"
      linters:
        - lll
    - path: "injector.go"
      linters:
        - lll
